### PR TITLE
Dead code removal & standardizing naming for consistency

### PR DESCRIPTION
**Pull request by tomaz**
The before mentioned naming consistency and (some) dead code removal:

- rename all forms to `<Name>Form`
- use consistent case (capitalized for class names, methods and properties, camel case for variables/controls)
- add more descriptive and consistent names to controls (for example suffix includes control type)
- encapsulation for forms - no more direct access of controls from outside, all data flow is implemented through `Model` or public members

But also couple minor improvements:

- project name form offers current name if available
- pressing enter in project name form will accept the text
- comment type is persisted in project file
- if palette is offered when make blocks is clicked, it will automatically resume with make blocks after palette form is confirmed

### CODE REVIEW

**Comment by tomaz** [comment]
Oh, the following forms are not used in current codebase (maybe they're used with your private additions, so I left it in). Original names:

- `Progress`
- `fileTree`
- `rebuild`

If you don't use these either, let me know and I can remove them before merging

**Comment by infromthecold** [comment]
You might find some stuff i have done was from an old code base, however
progress was probably a progress bar, which is now in the status, file tree
may have been where i was going to have a project structure  like VS, which
did not work out and well rebuild, who knows?

**Comment by infromthecold** [comment]
Merged

**Comment by tomaz** [comment]
> and well rebuild, who knows

😂😂😂😂

I'll remove those in later PR then

The game looks amazing!

**Pull request merged**
