### PR TITLE
Refactoring export into external class

### PR DESCRIPTION
**Pull request by tomaz**
Main focus points:

- move export code out of main form thus making it accessible outside UI (for example allow use from cmd line)
- each distinct export file generator is implemented as its own class; this makes code more managable and extendable

Similar to previous PR, I used unit tests to ensure export data is the same. My projects also are exported correctly, but they're simple so maybe there are smaller aspects I missed.

Other notes:

- fixed bug I introduced in previous PR where palette form would always select next 256 palette
- DRYed couple repetitive parts in export code, mainly the ones dealing with individual blocks/chars data that were repeated in many places and/or made overall export algorithm harder to understand
- sprite tile images now respect image format from settings
- main form is now more structured:
    - each event is implemented as its own method and if multiple events use the same underlying code, a private helper method is used
    - grouped "related" methods into regions to allow collapsing and thus reduce scrolling when only interested in particular parts
    - renamed generic control names into more meaningful ones to be able to better understand and reason with code
    - tool bar and menus are disabled while performing lenghtier operations to avoid dealing with interruptions due to double clicking
    - renamed the file and class to `MainForm` for consistency

### CODE REVIEW

**Comment by infromthecold** [comment]
I think we don't need the bitmap part of the bitsBitmap, try it by
commenting these lines in "supportingClasses.cs"

line 45ish

//protected GCHandle BitsHandle { get; private set; }

line 60ish

//BitsHandle = GCHandle.Alloc(Bits, GCHandleType.Pinned);
//Bitmap = new Bitmap(width, height, width,
PixelFormat.Format8bppIndexed,BitsHandle.AddrOfPinnedObject());

and this one

//Bitmap.Dispose();

Around line 102ish

As we are only accessing the array that the bitsBitmap creates

**Comment by tomaz** [comment]
Yeah, good point. I left unused methods where I wasn't sure on whether they're left overs or work in progress...

**Comment by infromthecold** [comment]
You are doing an amazing job, I just write to make it work for what i need,
you are expanding my work beyond what I expected it would be, thank you.

Yeah BitsHandle can also go, they were used to make use of all the Bitmap
functions from the array, as that's where it started, and i think the code
does not make use of them, I one plan was to make it export (maybe through
some templates) to other retro machines like c64 or Amiga, as it could be
more widely used and it does a good job at creating tile/character sets.
But i dont have the time at the moment.

**Comment by tomaz** [comment]
With recent changes, adding support for C64/Amiga and other platforms should be simpler, but still substantial work. But it can be done, when more concrete need for it arises. Though it should be further simplified when I start working on templates. I'll check for dead code next, and maybe standardize naming for remaining forms before adding new features, seems like a nice small improvement in between bigger stuff...

**Comment by infromthecold** [comment]
I have been working on separate copy of that code, as i have more
proprietor stuff gone in and a few changes to get it to do what i need it
to, so when i get time i will do a pull and integrate my changes, then
probably around February release my proprietor stuff too, so it can do all
the features, also I will be releasing my bezier/map editor at that time
too which may need you touch :)

Happy new year Tomaz
Trish

**Pull request merged**
